name: Android CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [30]
        target: [default]
        flavor: [none]
        build-tools: [30.0.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download and setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          flavor: ${{ matrix.flavor }}
          build-tools: ${{ matrix.build-tools }}

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build